### ISSUE TITLE
Issue with small barre code

### ISSUE THREAD

**Issue by gillouz** [sosandroid/Code39-barcode-FPDF#2]
Hi I use a Zebra printer GK420d and I had issue on small barre code

I found a solution by changing slightly this function

`function draw_code39($code, $x, $y, $w, $h) {
//Draw bars
for($i=0; $i<strlen($code); $i++) {
if($code[$i] == '1')
{
 $this->SetFillColor(0,0,0);
 $this->Rect($x+$i*$w, $y, $w, $h, 'F');
}
else // draw white rect on 0
{
 $this->SetFillColor(255,255,255);
 $this->Rect($x+$i*$w, $y, $w , $h, 'F');
}
}
}`

**Comment by sosandroid** [comment]
Merci pour la proposition. C'est intégré

Thank for this improvement proposal. This lead me to think that this lib need refactoring
